### ISSUE TITLE
Screen sharing not working on live. 

### ISSUE THREAD

**Issue by kamran-jabbar** [philnash/screen-capture#2]
First I setup code on local and launch the extension in store, that was working fine as expected on local.
After that, I deployed the app on AWS server and everything is working fine but screen sharing is causing some issue. I changed the extension id as well. 
App URL:  https://share.acdmia.com/
Extension URL: https://chrome.google.com/webstore/detail/hkdfoccdjkmhkfgfmapladgfkbpameej
Error in the console:
![screenshot_1](https://user-images.githubusercontent.com/35640191/44048644-5a94adde-9f4b-11e8-9c44-2b7f55ff8758.png)
How can I fix this issue ?
Any help will be appreciated.
Thanks

**Comment by philnash** [comment]
Did you update the extension manifest to include your URL in the `externally_connectable.matches` array?

**Comment by kamran-jabbar** [comment]
Issue found in extension `manifest.json`. 
I forgot to replace 
`"matches": ["*://localhost/*"]` to  `"matches": ["*://share.acdmia.com/*"]`
Please update read.md file for those who don't know about extensions code. 
Thanks for the quick help.

**Comment by philnash** [comment]
Glad to hear that worked. I’m actually on holiday myself right now, so if you could make a pull request to update the readme, that would be really useful! Thanks!

**Comment by kamran-jabbar** [comment]
Ok sure, I am going to do that.

**Comment by kamran-jabbar** [comment]
If you deployed the application on the live server then you have to update domain name of the deployed application in extension `extension/manifest.json` file.
`externally_connectable.matches` array `["*://localhost/*"]` to `["*://yourdomain.com/*"]` and launch the application in chrome web store. 

Add it in the readme, thanks.
